# Generated by Django 2.1.5 on 2019-01-09 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('author', models.CharField(max_length=50)),
                ('detail', models.CharField(max_length=128)),
                ('year', models.IntegerField()),
                ('status', models.CharField(choices=[('A', 'available'), ('O', 'checked-out')], default='available', max_length=50)),
                ('date_added', models.DateField(auto_now_add=True)),
                ('last_borrowed', models.DateField(auto_now=True)),
            ],
        ),
    ]
