# Generated by Django 2.1.5 on 2019-01-09 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lender_books', '0002_book_cover_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover_image',
            field=models.ImageField(default='static/image/no-img.jpg', upload_to='static/image/'),
        ),
    ]
