# Generated by Django 2.1.5 on 2019-01-09 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lender_books', '0004_auto_20190109_2152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover_image',
            field=models.ImageField(default='no-img.jpg', upload_to='media'),
        ),
    ]
