# Generated by Django 2.1.5 on 2019-01-11 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lender_books', '0005_auto_20190109_2338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='last_borrowed',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
